# Generated by Django 4.2.2 on 2023-06-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='hello', upload_to='pic'),
            preserve_default=False,
        ),
    ]
